Add part 8, 9, 10. Fix indentation issues.
Xcho19/OrderApp pull request #5
Opened 2022-03-03 19:02 UTC by Xcho19

2022-03-07 09:41 UTC, hovaks requested changes

2022-03-07 09:41 UTC, hovaks commented on OrderApp/Controllers/CategoryTableViewController.swift
>          Task.init {
ինիտ գրելու կարիք չկա

2022-03-07 09:41 UTC, hovaks commented on OrderApp/Controllers/MenuItemDetailViewController.swift
> +        Task.init {
ստեղ էլ

2022-03-07 09:41 UTC, hovaks commented on OrderApp/Controllers/MenuTableViewController.swift
> +        imageLoadTasks.forEach { _, value in value.cancel() }
նայի էսի id։ task-երի dict ա չէ, նախ կարաիր մենակ վելյուների վրա ֆռռայիր, եթե սենց էլ, ավելի լավ ա closure-ի պարամետրի անունը task դնել, քան value

2022-03-07 09:41 UTC, hovaks commented on OrderApp/Controllers/MenuTableViewController.swift
> +        imageLoadTasks[indexPath] = Task.init {
init-ը

2022-03-07 09:41 UTC, hovaks commented on OrderApp/Controllers/MenuTableViewController.swift
> +        -> Int { menuItems.count }
մալադեց

2022-03-07 09:41 UTC, hovaks commented on OrderApp/Controllers/OrderTableViewController.swift
> +        Task.init {
ինիտը

2022-03-07 09:41 UTC, hovaks commented on OrderApp/Controllers/OrderTableViewController.swift
> +        imageLoadTasks[indexPath] = Task.init {
ինիտը

2022-03-07 09:41 UTC, hovaks commented on OrderApp/Controllers/OrderTableViewController.swift
> +        OrderConfirmationViewController.init(coder: coder, minutesToPrepare: minutesToPrepareOrder)
ստեղ էլ ինիտ պետք չի

2022-03-07 09:41 UTC, hovaks commented on OrderApp/Controllers/OrderTableViewController.swift
> +            handler: { _ in
էս հենդլերը trailing closure-ով գրի

2022-03-07 09:41 UTC, hovaks commented on OrderApp/Controllers/OrderTableViewController.swift
> +    -> Bool { true }
։Ճ

2022-03-07 12:47 UTC, Xcho19 commented on OrderApp/Controllers/MenuTableViewController.swift
> +        imageLoadTasks.forEach { _, value in value.cancel() }
Es pahy chpatkeracreci vonc anem.

2022-03-15 16:34 UTC, hovaks approved these changes

2022-03-15 16:34 UTC, merged